server.servlet.context-path=/web

context.initializer.classes=com.blue.fish.source.initializer.ThirdInitializer,com.blue.fish.source.initializer.FourthInitializer

context.listener.classes=com.blue.fish.source.listener.ThirdListener