server.servlet.context-path=/web

context.initializer.classes=com.blue.fish.source.initializer.ThirdInitializer,com.blue.fish.source.initializer.FourthInitializer

context.listener.classes=com.blue.fish.source.listener.ThirdListener

spring.banner.location=favorite.txt
spring.banner.image.location=favorite.jpg

spring.main.banner-mode=off

banner.tag=application

spring.profiles.active=online

#spring.profiles.include=online,prod
